import {
  Accordion,
  AccordionItem,
  Button,
  Column,
  DataTable,
  FileUploaderDropContainer,
  FileUploaderItem,
  Grid,
  InlineNotification,
  Loading,
  Modal,
  Select,
  SelectItem,
  StructuredListBody,
  StructuredListCell,
  StructuredListHead,
  StructuredListRow,
  StructuredListWrapper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableHeader,
  TableRow,
  Tag,
} from "@carbon/react";
import { Checkmark, ChevronLeft, Download, Warning } from "@carbon/react/icons";
import { useCallback, useMemo, useState } from "react";
import { useIntl } from "react-intl";
import { postToOpenElisServerFormDataJson } from "../../utils/Utils";

/**
 * GenericManifestImportModal — lab-agnostic 4-step manifest import.
 *
 * Driven entirely by {@code pageData.config} (falls back to pageData.data):
 *   manifestColumns      — column schema; each entry may include:
 *                            required, description, example, aliases,
 *                            validValues (inline list of accepted values)
 *   columns              — columns to show in the sample grid after import
 *   autoGeneratedFields  — fields the system creates (not expected in CSV)
 *
 * Steps:
 *  1. upload  — file drop zone + full field reference accordion
 *  2. map     — column mapping: user selects which CSV column → each expected field
 *  3. preview — client-side validation summary + error list + preview table
 *  4. success — confirmation (importSuccess state renders inline; no extra step)
 *
 * @param {boolean}  open             Modal open state
 * @param {function} onClose          Called when modal is dismissed
 * @param {number}   entryId          Notebook entry ID
 * @param {Object}   pageData         Template page object
 * @param {function} onImportSuccess  Called with result after successful import
 */
function GenericManifestImportModal({
  open,
  onClose,
  entryId,
  pageData,
  onImportSuccess,
}) {
  const intl = useIntl();

  const configSource = pageData?.config ?? pageData?.data ?? {};
  const manifestColumns = configSource?.manifestColumns ?? [];
  const displayColumns = configSource?.columns ?? [];
  const autoGeneratedFields = configSource?.autoGeneratedFields ?? [];

  const requiredCols = useMemo(
    () => manifestColumns.filter((c) => c.required),
    [manifestColumns],
  );
  const optionalCols = useMemo(
    () => manifestColumns.filter((c) => !c.required),
    [manifestColumns],
  );

  const [step, setStep] = useState("upload");
  const [file, setFile] = useState(null);
  const [fileError, setFileError] = useState(null);
  const [csvHeaders, setCsvHeaders] = useState([]); // columns detected in user's CSV
  const [columnMapping, setColumnMapping] = useState({});
  const [parsedRows, setParsedRows] = useState([]);
  const [validRows, setValidRows] = useState([]);
  const [invalidRows, setInvalidRows] = useState([]);
  const [loading, setLoading] = useState(false);
  const [importError, setImportError] = useState(null);
  const [importSuccess, setImportSuccess] = useState(null);

  /**
   * Normalize a header string for fuzzy matching:
   * lowercase, strip spaces / underscores / hyphens / slashes.
   */
  const normalize = (s) => (s ?? "").toLowerCase().replace(/[\s_\-/]+/g, "");

  /**
   * Build a map of  normalizedAlias → field  from manifestColumns.
   * Checks (in order): the aliases array, the csvHeader itself, the label.
   */
  const buildAliasMap = useCallback(() => {
    const aliasMap = {}; // normalized → field
    manifestColumns.forEach((col) => {
      const field = col.field;
      if (!field) return;

      const register = (val) => {
        const n = normalize(val);
        if (n && !aliasMap[n]) aliasMap[n] = field;
      };

      // Explicit aliases array
      (col.aliases ?? []).forEach(register);
      // csvHeader itself
      register(col.csvHeader);
      // Label as fallback
      register(col.label);
    });
    return aliasMap;
  }, [manifestColumns]);

  /**
   * Given a list of CSV column headers, try to auto-map each manifestColumn
   * to the best matching CSV header.  Returns { field → csvHeaderOrEmpty }.
   */
  const autoMap = useCallback(
    (headers) => {
      const aliasMap = buildAliasMap();
      const mapping = {};

      // Initialize all fields to ""
      manifestColumns.forEach((c) => {
        if (c.field) mapping[c.field] = "";
      });

      headers.forEach((h) => {
        const norm = normalize(h);
        const field = aliasMap[norm];
        if (field && !mapping[field]) {
          mapping[field] = h;
        }
      });

      return mapping;
    },
    [buildAliasMap, manifestColumns],
  );

  const parseCsvLine = (line) => {
    const result = [];
    let current = "";
    let inQuotes = false;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (ch === '"') {
        if (inQuotes && line[i + 1] === '"') {
          current += '"';
          i++;
        } else {
          inQuotes = !inQuotes;
        }
      } else if (ch === "," && !inQuotes) {
        result.push(current);
        current = "";
      } else {
        current += ch;
      }
    }
    result.push(current);
    return result;
  };

  /**
   * Read only the first line of the CSV to extract headers and auto-map.
   */
  const extractCsvHeaders = useCallback(
    (csvFile) => {
      const reader = new FileReader();
      reader.onload = (e) => {
        const text = e.target.result;
        const firstLine = text.split(/\r?\n/)[0] ?? "";
        const headers = parseCsvLine(firstLine).map((h) => h.trim());
        setCsvHeaders(headers);
        setColumnMapping(autoMap(headers));
        setStep("map");
      };
      reader.readAsText(csvFile);
    },
    [autoMap],
  );

  /**
   * Parse ALL rows using the current columnMapping.
   * Returns { allRows, valid, invalid }.
   */
  const parseAllRows = useCallback(
    (csvFile, mapping) => {
      return new Promise((resolve) => {
        const reader = new FileReader();
        reader.onload = (e) => {
          const text = e.target.result;
          const lines = text.split(/\r?\n/).filter((l) => l.trim());
          if (lines.length < 2) {
            resolve({ allRows: [], valid: [], invalid: [] });
            return;
          }

          const rawHeaders = parseCsvLine(lines[0]).map((h) => h.trim());
          // Build index: csvHeader → column index
          const headerIndex = {};
          rawHeaders.forEach((h, i) => {
            headerIndex[h] = i;
          });

          const allRows = [];
          for (let i = 1; i < lines.length; i++) {
            const vals = parseCsvLine(lines[i]);
            const rowObj = { __rowNumber: i + 1 };

            // For each manifest field, look up the user-selected CSV column
            manifestColumns.forEach((col) => {
              const selectedCsvCol = mapping[col.field] ?? "";
              if (selectedCsvCol) {
                const idx = headerIndex[selectedCsvCol];
                rowObj[col.field] =
                  idx !== undefined ? (vals[idx] ?? "").trim() : "";
              } else {
                rowObj[col.field] = "";
              }
            });

            allRows.push(rowObj);
          }

          // Validate required fields and constrained validValues
          const valid = [];
          const invalid = [];
          allRows.forEach((row) => {
            const errors = [];
            manifestColumns.forEach((col) => {
              const val = row[col.field];
              // Required check
              if (col.required && (!val || val === "")) {
                errors.push(
                  intl.formatMessage(
                    {
                      id: "notebook.manifest.error.missingRequired",
                      defaultMessage: "Missing required field: {field}",
                    },
                    { field: col.label ?? col.field },
                  ),
                );
              }
              // validValues check — case-insensitive, only when a value is present
              if (
                val &&
                val !== "" &&
                Array.isArray(col.validValues) &&
                col.validValues.length > 0 &&
                !col.validValues.some(
                  (v) => v.toLowerCase() === val.toLowerCase(),
                )
              ) {
                errors.push(
                  intl.formatMessage(
                    {
                      id: "notebook.manifest.error.invalidValue",
                      defaultMessage:
                        'Invalid value for {field}: "{value}". Expected one of: {allowed}',
                    },
                    {
                      field: col.label ?? col.field,
                      value: val,
                      allowed: col.validValues.join(", "),
                    },
                  ),
                );
              }
            });
            if (errors.length > 0) {
              invalid.push({ rowNumber: row.__rowNumber, errors, ...row });
            } else {
              valid.push(row);
            }
          });

          resolve({ allRows, valid, invalid });
        };
        reader.readAsText(csvFile);
      });
    },
    [manifestColumns, requiredCols, intl],
  );

  const handleFileAdded = useCallback(
    (_, { addedFiles }) => {
      const f = addedFiles[0];
      if (!f) return;
      if (!f.name.toLowerCase().endsWith(".csv")) {
        setFileError(
          intl.formatMessage({
            id: "notebook.manifest.error.invalidFileType",
            defaultMessage: "Please upload a CSV file.",
          }),
        );
        return;
      }
      setFile(f);
      setFileError(null);
      setImportError(null);
      setImportSuccess(null);
      setParsedRows([]);
      setValidRows([]);
      setInvalidRows([]);
      extractCsvHeaders(f);
    },
    [intl, extractCsvHeaders],
  );

  const handleRemoveFile = useCallback(() => {
    setFile(null);
    setFileError(null);
    setCsvHeaders([]);
    setColumnMapping({});
    setParsedRows([]);
    setValidRows([]);
    setInvalidRows([]);
    setStep("upload");
    setImportError(null);
    setImportSuccess(null);
  }, []);

  const handleMappingChange = useCallback((field, csvCol) => {
    setColumnMapping((prev) => ({ ...prev, [field]: csvCol }));
  }, []);

  const requiredFieldsMapped = useMemo(
    () => requiredCols.every((col) => columnMapping[col.field]),
    [requiredCols, columnMapping],
  );

  const autoMappedCount = useMemo(
    () => Object.values(columnMapping).filter((v) => v && v !== "").length,
    [columnMapping],
  );

  const handleGoToPreview = useCallback(async () => {
    if (!file || !requiredFieldsMapped) return;
    const { allRows, valid, invalid } = await parseAllRows(file, columnMapping);
    setParsedRows(allRows);
    setValidRows(valid);
    setInvalidRows(invalid);
    setStep("preview");
  }, [file, requiredFieldsMapped, parseAllRows, columnMapping]);

  const handleImport = useCallback(() => {
    if (!file || validRows.length === 0) return;
    setLoading(true);
    setImportError(null);

    const formData = new FormData();
    formData.append("file", file);
    // Send the user-chosen mapping: { field → selectedCsvColumnName }
    formData.append("columnMapping", JSON.stringify(columnMapping));

    postToOpenElisServerFormDataJson(
      `/rest/notebook/entry/${entryId}/page/${pageData?.id}/import-manifest`,
      formData,
      (response) => {
        setLoading(false);
        if (response?.success) {
          setImportSuccess(
            intl.formatMessage(
              {
                id: "notebook.manifest.success",
                defaultMessage: "Successfully imported {count} sample(s).",
              },
              { count: response.totalCreated ?? validRows.length },
            ),
          );
          if (onImportSuccess) onImportSuccess(response);
        } else {
          const msgs = (response?.errors ?? [])
            .map((e) => `Row ${e.rowNumber}: ${e.message}`)
            .join("; ");
          setImportError(
            response?.error
              ? `${response.error}${msgs ? ` — ${msgs}` : ""}`
              : intl.formatMessage({
                  id: "notebook.manifest.error.generic",
                  defaultMessage:
                    "Import failed. Please check the file and try again.",
                }),
          );
        }
      },
    );
  }, [
    file,
    columnMapping,
    entryId,
    pageData,
    validRows.length,
    intl,
    onImportSuccess,
  ]);

  const handleClose = useCallback(() => {
    setStep("upload");
    setFile(null);
    setFileError(null);
    setCsvHeaders([]);
    setColumnMapping({});
    setParsedRows([]);
    setValidRows([]);
    setInvalidRows([]);
    setLoading(false);
    setImportError(null);
    setImportSuccess(null);
    onClose();
  }, [onClose]);

  const handleDownloadTemplate = useCallback(() => {
    const headers = manifestColumns.map((c) => c.csvHeader).join(",");
    const makeExampleRow = (colIndex) =>
      manifestColumns
        .map((c) => {
          const raw = c.example ?? "";
          const parts = raw.split(/\s*[,/]\s*/);
          const val = (parts[colIndex] ?? parts[0] ?? "").trim();
          return val.includes(",") ? `"${val}"` : val;
        })
        .join(",");

    const csv = [headers, makeExampleRow(0), makeExampleRow(1)].join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const labTitle = (pageData?.title ?? "manifest").replace(/\s+/g, "_");
    a.download = `${labTitle}_template.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }, [manifestColumns, pageData]);

  const previewTableColumns = useMemo(() => {
    if (displayColumns.length > 0) return displayColumns;
    return manifestColumns.slice(0, 4).map((c) => ({
      key: c.field,
      header: c.label ?? c.field,
    }));
  }, [displayColumns, manifestColumns]);

  const primaryButtonText = (() => {
    if (loading) return <Loading small withOverlay={false} />;
    if (step === "map")
      return intl.formatMessage({
        id: "notebook.manifest.previewBtn",
        defaultMessage: "Preview",
      });
    if (step === "preview")
      return intl.formatMessage({
        id: "notebook.manifest.import",
        defaultMessage: "Import Samples",
      });
    return intl.formatMessage({
      id: "label.button.next",
      defaultMessage: "Next",
    });
  })();

  const primaryDisabled = (() => {
    if (loading) return true;
    if (step === "upload") return !file;
    if (step === "map") return !requiredFieldsMapped;
    if (step === "preview") return validRows.length === 0 || !!importSuccess;
    return false;
  })();

  const handlePrimary = () => {
    if (step === "map") return handleGoToPreview();
    if (step === "preview") return handleImport();
  };

  const NONE_VALUE = "__none__";
  const csvColOptions = [
    { value: NONE_VALUE, label: "— Not mapped —" },
    ...csvHeaders.map((h) => ({ value: h, label: h })),
  ];

  return (
    <Modal
      open={open}
      onRequestClose={handleClose}
      modalHeading={intl.formatMessage({
        id: "notebook.manifest.modal.title",
        defaultMessage: "Import Samples from Manifest",
      })}
      primaryButtonText={primaryButtonText}
      secondaryButtonText={intl.formatMessage({
        id: "label.button.cancel",
        defaultMessage: "Cancel",
      })}
      primaryButtonDisabled={primaryDisabled}
      onRequestSubmit={handlePrimary}
      size="lg"
    >
      <div
        style={{
          display: "flex",
          gap: "0.5rem",
          marginBottom: "1.25rem",
          alignItems: "center",
        }}
      >
        {["upload", "map", "preview"].map((s, i) => (
          <Tag key={s} type={step === s ? "blue" : "gray"} size="sm">
            {i + 1}.{" "}
            {s === "upload"
              ? intl.formatMessage({
                  id: "notebook.manifest.step.upload",
                  defaultMessage: "Upload",
                })
              : s === "map"
                ? intl.formatMessage({
                    id: "notebook.manifest.step.mapColumns",
                    defaultMessage: "Map Columns",
                  })
                : intl.formatMessage({
                    id: "notebook.manifest.step.preview",
                    defaultMessage: "Preview & Import",
                  })}
          </Tag>
        ))}
      </div>

      {step === "upload" && (
        <div>
          {/* Template download */}
          <div style={{ marginBottom: "1rem" }}>
            <Button
              kind="ghost"
              size="sm"
              renderIcon={Download}
              onClick={handleDownloadTemplate}
            >
              {intl.formatMessage({
                id: "notebook.manifest.downloadTemplate",
                defaultMessage: "Download CSV Template",
              })}
            </Button>
          </div>

          {/* Drop zone */}
          {!file ? (
            <FileUploaderDropContainer
              accept={[".csv"]}
              labelText={intl.formatMessage({
                id: "notebook.manifest.dropzone",
                defaultMessage:
                  "Drag and drop a CSV file here, or click to upload",
              })}
              onAddFiles={handleFileAdded}
            />
          ) : (
            <FileUploaderItem
              name={file.name}
              status="edit"
              onDelete={handleRemoveFile}
            />
          )}

          {fileError && (
            <InlineNotification
              kind="error"
              title={fileError}
              hideCloseButton
              lowContrast
              style={{ marginTop: "0.75rem" }}
            />
          )}

          {/* Field reference accordion */}
          <Accordion style={{ marginTop: "1.5rem" }}>
            {/* Required fields */}
            {requiredCols.length > 0 && (
              <AccordionItem
                title={
                  <span>
                    {intl.formatMessage({
                      id: "notebook.manifest.requiredFields",
                      defaultMessage: "Required Fields",
                    })}
                    <Tag type="red" size="sm" style={{ marginLeft: "0.5rem" }}>
                      {requiredCols.length}
                    </Tag>
                  </span>
                }
              >
                <StructuredListWrapper>
                  <StructuredListHead>
                    <StructuredListRow head>
                      <StructuredListCell head>
                        {intl.formatMessage({
                          id: "notebook.manifest.col.header",
                          defaultMessage: "CSV Header",
                        })}
                      </StructuredListCell>
                      <StructuredListCell head>
                        {intl.formatMessage({
                          id: "notebook.manifest.col.label",
                          defaultMessage: "Field",
                        })}
                      </StructuredListCell>
                      <StructuredListCell head>
                        {intl.formatMessage({
                          id: "notebook.manifest.col.description",
                          defaultMessage: "Description",
                        })}
                      </StructuredListCell>
                      <StructuredListCell head>
                        {intl.formatMessage({
                          id: "notebook.manifest.col.example",
                          defaultMessage: "Example",
                        })}
                      </StructuredListCell>
                    </StructuredListRow>
                  </StructuredListHead>
                  <StructuredListBody>
                    {requiredCols.map((col) => (
                      <StructuredListRow key={col.field}>
                        <StructuredListCell noWrap>
                          <code>{col.csvHeader}</code>
                        </StructuredListCell>
                        <StructuredListCell>
                          <strong>{col.label ?? col.field}</strong>
                        </StructuredListCell>
                        <StructuredListCell>
                          <span>{col.description ?? "—"}</span>
                          {Array.isArray(col.validValues) &&
                            col.validValues.length > 0 && (
                              <div
                                style={{
                                  display: "flex",
                                  flexWrap: "wrap",
                                  gap: "0.25rem",
                                  marginTop: "0.35rem",
                                }}
                              >
                                {col.validValues.map((v) => (
                                  <Tag key={v} type="purple" size="sm">
                                    {v}
                                  </Tag>
                                ))}
                              </div>
                            )}
                        </StructuredListCell>
                        <StructuredListCell>
                          <em>{col.example ?? "—"}</em>
                        </StructuredListCell>
                      </StructuredListRow>
                    ))}
                  </StructuredListBody>
                </StructuredListWrapper>
              </AccordionItem>
            )}

            {/* Optional fields */}
            {optionalCols.length > 0 && (
              <AccordionItem
                title={
                  <span>
                    {intl.formatMessage({
                      id: "notebook.manifest.optionalFields",
                      defaultMessage: "Optional Fields",
                    })}
                    <Tag type="blue" size="sm" style={{ marginLeft: "0.5rem" }}>
                      {optionalCols.length}
                    </Tag>
                  </span>
                }
              >
                <StructuredListWrapper>
                  <StructuredListHead>
                    <StructuredListRow head>
                      <StructuredListCell head>
                        {intl.formatMessage({
                          id: "notebook.manifest.col.header",
                          defaultMessage: "CSV Header",
                        })}
                      </StructuredListCell>
                      <StructuredListCell head>
                        {intl.formatMessage({
                          id: "notebook.manifest.col.label",
                          defaultMessage: "Field",
                        })}
                      </StructuredListCell>
                      <StructuredListCell head>
                        {intl.formatMessage({
                          id: "notebook.manifest.col.description",
                          defaultMessage: "Description",
                        })}
                      </StructuredListCell>
                      <StructuredListCell head>
                        {intl.formatMessage({
                          id: "notebook.manifest.col.example",
                          defaultMessage: "Example",
                        })}
                      </StructuredListCell>
                      <StructuredListCell head>
                        {intl.formatMessage({
                          id: "notebook.manifest.col.category",
                          defaultMessage: "Category",
                        })}
                      </StructuredListCell>
                    </StructuredListRow>
                  </StructuredListHead>
                  <StructuredListBody>
                    {optionalCols.map((col) => (
                      <StructuredListRow key={col.field}>
                        <StructuredListCell noWrap>
                          <code>{col.csvHeader}</code>
                        </StructuredListCell>
                        <StructuredListCell>
                          {col.label ?? col.field}
                        </StructuredListCell>
                        <StructuredListCell>
                          <span>{col.description ?? "—"}</span>
                          {Array.isArray(col.validValues) &&
                            col.validValues.length > 0 && (
                              <div
                                style={{
                                  display: "flex",
                                  flexWrap: "wrap",
                                  gap: "0.25rem",
                                  marginTop: "0.35rem",
                                }}
                              >
                                {col.validValues.map((v) => (
                                  <Tag key={v} type="purple" size="sm">
                                    {v}
                                  </Tag>
                                ))}
                              </div>
                            )}
                        </StructuredListCell>
                        <StructuredListCell>
                          <em>{col.example ?? "—"}</em>
                        </StructuredListCell>
                        <StructuredListCell>
                          {col.category ? (
                            <Tag type="blue" size="sm">
                              {col.category}
                            </Tag>
                          ) : (
                            "—"
                          )}
                        </StructuredListCell>
                      </StructuredListRow>
                    ))}
                  </StructuredListBody>
                </StructuredListWrapper>
              </AccordionItem>
            )}

            {/* Auto-generated fields */}
            {autoGeneratedFields.length > 0 && (
              <AccordionItem
                title={
                  <span>
                    {intl.formatMessage({
                      id: "notebook.manifest.autoGeneratedFields",
                      defaultMessage: "Auto-Generated Fields",
                    })}
                    <Tag
                      type="green"
                      size="sm"
                      style={{ marginLeft: "0.5rem" }}
                    >
                      {intl.formatMessage({
                        id: "notebook.manifest.notInCsv",
                        defaultMessage: "Not in CSV",
                      })}
                    </Tag>
                  </span>
                }
              >
                <p
                  style={{
                    fontSize: "0.875rem",
                    marginBottom: "0.75rem",
                    color: "#525252",
                  }}
                >
                  {intl.formatMessage({
                    id: "notebook.manifest.autoGeneratedInfo",
                    defaultMessage:
                      "These fields are automatically generated by the system. Do not include them in your CSV file.",
                  })}
                </p>
                <StructuredListWrapper>
                  <StructuredListHead>
                    <StructuredListRow head>
                      <StructuredListCell head>
                        {intl.formatMessage({
                          id: "notebook.manifest.col.label",
                          defaultMessage: "Field",
                        })}
                      </StructuredListCell>
                      <StructuredListCell head>
                        {intl.formatMessage({
                          id: "notebook.manifest.col.description",
                          defaultMessage: "Description",
                        })}
                      </StructuredListCell>
                    </StructuredListRow>
                  </StructuredListHead>
                  <StructuredListBody>
                    {autoGeneratedFields.map((f) => (
                      <StructuredListRow key={f.key}>
                        <StructuredListCell>
                          <strong>{f.label ?? f.key}</strong>
                        </StructuredListCell>
                        <StructuredListCell>
                          {f.description ?? "—"}
                        </StructuredListCell>
                      </StructuredListRow>
                    ))}
                  </StructuredListBody>
                </StructuredListWrapper>
              </AccordionItem>
            )}
          </Accordion>
        </div>
      )}

      {/* ══ STEP 2: MAP COLUMNS ═══════════════════════════════════════════════ */}
      {step === "map" && (
        <div>
          {/* Back + file name */}
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: "1rem",
              marginBottom: "1rem",
            }}
          >
            <Button
              kind="ghost"
              size="sm"
              renderIcon={ChevronLeft}
              onClick={handleRemoveFile}
            >
              {intl.formatMessage({
                id: "notebook.manifest.changeFile",
                defaultMessage: "Change file",
              })}
            </Button>
            <span style={{ fontSize: "0.875rem", color: "#525252" }}>
              <strong>{file?.name}</strong>
              {" — "}
              {intl.formatMessage(
                {
                  id: "notebook.manifest.columnsDetected",
                  defaultMessage: "{count} columns detected",
                },
                { count: csvHeaders.length },
              )}
            </span>
            <Tag type={autoMappedCount > 0 ? "green" : "red"} size="sm">
              {intl.formatMessage(
                {
                  id: "notebook.manifest.autoMapped",
                  defaultMessage: "{count} auto-mapped",
                },
                { count: autoMappedCount },
              )}
            </Tag>
          </div>

          <InlineNotification
            kind="info"
            title={intl.formatMessage({
              id: "notebook.manifest.mapInstructions",
              defaultMessage:
                "Map your CSV columns to the expected reception metadata fields. All required fields (marked *) must be mapped.",
            })}
            hideCloseButton
            lowContrast
            style={{ marginBottom: "1rem" }}
          />

          {/* Required fields mapping */}
          {requiredCols.length > 0 && (
            <div style={{ marginBottom: "1.5rem" }}>
              <h5
                style={{
                  fontSize: "0.875rem",
                  fontWeight: 600,
                  marginBottom: "0.5rem",
                  display: "flex",
                  alignItems: "center",
                  gap: "0.5rem",
                }}
              >
                {intl.formatMessage({
                  id: "notebook.manifest.requiredFields",
                  defaultMessage: "Required Fields",
                })}
                <Tag type="red" size="sm">
                  *{" "}
                  {intl.formatMessage({
                    id: "notebook.manifest.required",
                    defaultMessage: "Required",
                  })}
                </Tag>
              </h5>
              <Grid narrow>
                {requiredCols.map((col) => (
                  <Column key={col.field} lg={8} md={8} sm={4}>
                    <Select
                      id={`map-req-${col.field}`}
                      labelText={
                        <span>
                          <span style={{ color: "#da1e28" }}>* </span>
                          {col.label ?? col.field}
                          {col.description && (
                            <span
                              style={{
                                fontSize: "0.75rem",
                                color: "#6f6f6f",
                                marginLeft: "0.5rem",
                              }}
                            >
                              ({col.description})
                            </span>
                          )}
                        </span>
                      }
                      value={columnMapping[col.field] || NONE_VALUE}
                      onChange={(e) => {
                        const val = e.target.value;
                        handleMappingChange(
                          col.field,
                          val === NONE_VALUE ? "" : val,
                        );
                      }}
                      style={{ marginBottom: "1rem" }}
                    >
                      {csvColOptions.map((opt) => (
                        <SelectItem
                          key={opt.value}
                          value={opt.value}
                          text={opt.label}
                        />
                      ))}
                    </Select>
                  </Column>
                ))}
              </Grid>
            </div>
          )}

          {/* Optional fields mapping */}
          {optionalCols.length > 0 && (
            <Accordion>
              <AccordionItem
                title={
                  <span>
                    {intl.formatMessage({
                      id: "notebook.manifest.optionalMappings",
                      defaultMessage: "Optional Field Mappings",
                    })}
                    <Tag type="blue" size="sm" style={{ marginLeft: "0.5rem" }}>
                      {
                        optionalCols.filter((c) => columnMapping[c.field])
                          .length
                      }
                      /{optionalCols.length}{" "}
                      {intl.formatMessage({
                        id: "notebook.manifest.mapped",
                        defaultMessage: "mapped",
                      })}
                    </Tag>
                  </span>
                }
              >
                <Grid narrow>
                  {optionalCols.map((col) => (
                    <Column key={col.field} lg={8} md={8} sm={4}>
                      <Select
                        id={`map-opt-${col.field}`}
                        labelText={
                          <span>
                            {col.label ?? col.field}
                            {col.category && (
                              <Tag
                                type="blue"
                                size="sm"
                                style={{ marginLeft: "0.25rem" }}
                              >
                                {col.category}
                              </Tag>
                            )}
                          </span>
                        }
                        value={columnMapping[col.field] || NONE_VALUE}
                        onChange={(e) => {
                          const val = e.target.value;
                          handleMappingChange(
                            col.field,
                            val === NONE_VALUE ? "" : val,
                          );
                        }}
                        style={{ marginBottom: "1rem" }}
                      >
                        {csvColOptions.map((opt) => (
                          <SelectItem
                            key={opt.value}
                            value={opt.value}
                            text={opt.label}
                          />
                        ))}
                      </Select>
                    </Column>
                  ))}
                </Grid>
              </AccordionItem>
            </Accordion>
          )}

          {/* Detected CSV columns reference */}
          <div style={{ marginTop: "1rem" }}>
            <p
              style={{
                fontSize: "0.75rem",
                color: "#6f6f6f",
                marginBottom: "0.25rem",
              }}
            >
              {intl.formatMessage({
                id: "notebook.manifest.detectedColumns",
                defaultMessage: "Detected CSV columns:",
              })}
            </p>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "0.25rem" }}>
              {csvHeaders.map((h) => (
                <Tag key={h} type="gray" size="sm">
                  {h}
                </Tag>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* ══ STEP 3: PREVIEW & IMPORT ══════════════════════════════════════════ */}
      {step === "preview" && (
        <div>
          {/* Back to mapping */}
          <Button
            kind="ghost"
            size="sm"
            renderIcon={ChevronLeft}
            style={{ marginBottom: "1rem" }}
            onClick={() => setStep("map")}
          >
            {intl.formatMessage({
              id: "notebook.manifest.backToMapping",
              defaultMessage: "Back to column mapping",
            })}
          </Button>

          {/* Summary tags */}
          <Grid narrow style={{ marginBottom: "1rem" }}>
            <Column lg={4} md={4} sm={4}>
              <Tag type="blue">
                {intl.formatMessage({
                  id: "notebook.manifest.totalRows",
                  defaultMessage: "Total rows",
                })}
                {": "}
                {parsedRows.length}
              </Tag>
            </Column>
            <Column lg={4} md={4} sm={4}>
              <Tag type="green" renderIcon={Checkmark}>
                {intl.formatMessage({
                  id: "notebook.manifest.validRows",
                  defaultMessage: "Valid",
                })}
                {": "}
                {validRows.length}
              </Tag>
            </Column>
            {invalidRows.length > 0 && (
              <Column lg={4} md={4} sm={4}>
                <Tag type="red" renderIcon={Warning}>
                  {intl.formatMessage({
                    id: "notebook.manifest.invalidRows",
                    defaultMessage: "Errors",
                  })}
                  {": "}
                  {invalidRows.length}
                </Tag>
              </Column>
            )}
          </Grid>

          {/* Validation errors */}
          {invalidRows.length > 0 && (
            <Accordion style={{ marginBottom: "1rem" }}>
              <AccordionItem
                title={intl.formatMessage(
                  {
                    id: "notebook.manifest.validationErrors",
                    defaultMessage: "Validation Errors ({count} rows)",
                  },
                  { count: invalidRows.length },
                )}
              >
                <InlineNotification
                  kind="warning"
                  title={intl.formatMessage({
                    id: "notebook.manifest.errorsWillSkip",
                    defaultMessage:
                      "Rows with errors will be skipped during import. Fix the CSV and re-upload, or adjust the column mapping.",
                  })}
                  hideCloseButton
                  lowContrast
                  style={{ marginBottom: "0.75rem" }}
                />
                <StructuredListWrapper>
                  <StructuredListHead>
                    <StructuredListRow head>
                      <StructuredListCell head>
                        {intl.formatMessage({
                          id: "notebook.manifest.col.row",
                          defaultMessage: "Row",
                        })}
                      </StructuredListCell>
                      <StructuredListCell head>
                        {intl.formatMessage({
                          id: "notebook.manifest.col.errors",
                          defaultMessage: "Errors",
                        })}
                      </StructuredListCell>
                    </StructuredListRow>
                  </StructuredListHead>
                  <StructuredListBody>
                    {invalidRows.map((row) => (
                      <StructuredListRow key={row.rowNumber}>
                        <StructuredListCell noWrap>
                          {row.rowNumber}
                        </StructuredListCell>
                        <StructuredListCell>
                          {row.errors.join("; ")}
                        </StructuredListCell>
                      </StructuredListRow>
                    ))}
                  </StructuredListBody>
                </StructuredListWrapper>
              </AccordionItem>
            </Accordion>
          )}

          {/* Preview table — valid rows only */}
          {validRows.length > 0 && (
            <Accordion>
              <AccordionItem
                title={intl.formatMessage(
                  {
                    id: "notebook.manifest.previewTitle",
                    defaultMessage: "Preview ({count} valid rows)",
                  },
                  { count: validRows.length },
                )}
              >
                <div style={{ overflowX: "auto" }}>
                  <DataTable
                    rows={validRows.slice(0, 10).map((r, i) => ({
                      id: String(i),
                      ...r,
                    }))}
                    headers={previewTableColumns.map((c) => ({
                      key: c.key,
                      header: c.header,
                    }))}
                    size="sm"
                  >
                    {({
                      rows,
                      headers,
                      getTableProps,
                      getHeaderProps,
                      getRowProps,
                    }) => (
                      <TableContainer>
                        <Table {...getTableProps()}>
                          <TableHead>
                            <TableRow>
                              {headers.map((h) => (
                                <TableHeader
                                  key={h.key}
                                  {...getHeaderProps({ header: h })}
                                >
                                  {h.header}
                                </TableHeader>
                              ))}
                            </TableRow>
                          </TableHead>
                          <TableBody>
                            {rows.map((row) => (
                              <TableRow key={row.id} {...getRowProps({ row })}>
                                {row.cells.map((cell) => (
                                  <TableCell key={cell.id}>
                                    {cell.value || "—"}
                                  </TableCell>
                                ))}
                              </TableRow>
                            ))}
                          </TableBody>
                        </Table>
                      </TableContainer>
                    )}
                  </DataTable>
                  {validRows.length > 10 && (
                    <p
                      style={{
                        fontSize: "0.85rem",
                        color: "#525252",
                        marginTop: "0.5rem",
                      }}
                    >
                      {intl.formatMessage(
                        {
                          id: "notebook.manifest.previewTruncated",
                          defaultMessage:
                            "Showing first 10 of {count} valid rows.",
                        },
                        { count: validRows.length },
                      )}
                    </p>
                  )}
                </div>
              </AccordionItem>
            </Accordion>
          )}

          {validRows.length === 0 && (
            <InlineNotification
              kind="error"
              title={intl.formatMessage({
                id: "notebook.manifest.noValidRows",
                defaultMessage:
                  "No valid rows found. Please fix all errors or adjust the column mapping.",
              })}
              hideCloseButton
              lowContrast
            />
          )}
        </div>
      )}

      {importError && (
        <InlineNotification
          kind="error"
          title={importError}
          hideCloseButton
          lowContrast
          style={{ marginTop: "1rem" }}
        />
      )}
      {importSuccess && (
        <InlineNotification
          kind="success"
          title={importSuccess}
          hideCloseButton
          lowContrast
          style={{ marginTop: "1rem" }}
        />
      )}
    </Modal>
  );
}

export default GenericManifestImportModal;
