import {
  Microscope,
  CharacterWholeNumber,
  TableOfContents,
  ChartBubble,
  Catalog,
  Settings,
  ListDropdown,
  CicsSystemGroup,
  QrCode,
  ContainerSoftware,
  BootVolumeAlt,
  Report,
  Bullhorn,
  User,
  UserMultiple,
  BatchJob,
  ResultNew,
  Popup,
  Search,
  ConnectionSignal,
  Calendar,
  TrashCan,
  Translate,
  Calculator,
  Document,
  Notification,
  DataView,
  TextLinkAnalysis,
  Network_2,
  Devices,
  ScreenOff,
  ColorPalette,
} from "@carbon/icons-react";

export const adminMenuSections = [
  {
    id: "testCatalog",
    titleKey: "admin.section.testCatalog",
    defaultTitle: "Test Catalog",
    items: [
      {
        id: "testManagementConfigMenu",
        labelKey: "master.lists.page.test.management",
        path: "/admin/testManagementConfigMenu",
        icon: ResultNew,
        dataCy: "testManagementConfigMenu",
      },
      {
        id: "reflexTests",
        labelKey: "sidenav.label.admin.testmgt.reflex",
        path: "/admin/reflex",
        icon: Microscope,
        dataCy: "reflex",
      },
      {
        id: "calculatedValue",
        labelKey: "sidenav.label.admin.testmgt.calculated",
        path: "/admin/calculatedValue",
        icon: Calculator,
        dataCy: "calculatedValue",
      },
      {
        id: "analyzerTestName",
        labelKey: "sidenav.label.admin.analyzerTest",
        path: "/admin/AnalyzerTestName",
        icon: ListDropdown,
      },
      {
        id: "batchTestReassignment",
        labelKey: "configuration.batch.test.reassignment",
        path: "/admin/batchTestReassignment",
        icon: BatchJob,
        dataCy: "batchTestReassignment",
      },
    ],
  },
  {
    id: "usersOrgs",
    titleKey: "admin.section.usersOrgs",
    defaultTitle: "Users & Organizations",
    items: [
      {
        id: "userManagement",
        labelKey: "unifiedSystemUser.browser.title",
        path: "/admin/userManagement",
        icon: User,
        dataCy: "userMgmnt",
      },
      {
        id: "providerMenu",
        labelKey: "provider.browse.title",
        path: "/admin/providerMenu",
        icon: CicsSystemGroup,
        dataCy: "providerMgmnt",
      },
      {
        id: "organizationManagement",
        labelKey: "organization.main.title",
        path: "/admin/organizationManagement",
        icon: ContainerSoftware,
        dataCy: "orgMgmnt",
      },
    ],
  },
  {
    id: "labOps",
    titleKey: "admin.section.labOps",
    defaultTitle: "Lab Operations",
    items: [
      {
        id: "labNumber",
        labelKey: "sidenav.label.admin.labNumber",
        path: "/admin/labNumber",
        icon: CharacterWholeNumber,
        dataCy: "labNumberMgmnt",
      },
      {
        id: "program",
        labelKey: "sidenav.label.admin.program",
        path: "/admin/program",
        icon: ChartBubble,
        dataCy: "programEntry",
      },
      {
        id: "barcodeConfiguration",
        labelKey: "sidenav.label.admin.barcodeconfiguration",
        path: "/admin/barcodeConfiguration",
        icon: QrCode,
        dataCy: "barcodeConfig",
      },
      {
        id: "calendarManagement",
        labelKey: "calendar.management.title",
        path: "/admin/calendarManagement",
        icon: Calendar,
        dataCy: "calendarMgmnt",
      },
      {
        id: "resultReportingConfiguration",
        labelKey: "resultreporting.browse.title",
        path: "/admin/resultReportingConfiguration",
        icon: Report,
        dataCy: "resultReportingConfiguration",
      },
    ],
  },
  {
    id: "menuConfig",
    titleKey: "sidenav.label.admin.menu",
    defaultTitle: "Menu Configuration",
    items: [
      {
        id: "globalMenuManagement",
        labelKey: "sidenav.label.admin.menu.global",
        path: "/admin/globalMenuManagement",
        icon: TableOfContents,
        dataCy: "globalMenuMgmnt",
      },
      {
        id: "billingMenuManagement",
        labelKey: "sidenav.label.admin.menu.billing",
        path: "/admin/billingMenuManagement",
        icon: TableOfContents,
        dataCy: "billingMenuMgmnt",
      },
      {
        id: "nonConformityMenuManagement",
        labelKey: "sidenav.label.admin.menu.nonconform",
        path: "/admin/nonConformityMenuManagement",
        icon: TableOfContents,
        dataCy: "nonConformMenuMgmnt",
      },
      {
        id: "patientMenuManagement",
        labelKey: "sidenav.label.admin.menu.patient",
        path: "/admin/patientMenuManagement",
        icon: TableOfContents,
        dataCy: "patientMenuMgmnt",
      },
      {
        id: "studyMenuManagement",
        labelKey: "sidenav.label.admin.menu.study",
        path: "/admin/studyMenuManagement",
        icon: TableOfContents,
        dataCy: "studyMenuMgmnt",
      },
    ],
  },
  {
    id: "formEntry",
    titleKey: "admin.formEntryConfig",
    defaultTitle: "Form Entry Configuration",
    items: [
      {
        id: "nonConformityConfig",
        labelKey: "sidenav.label.admin.formEntry.nonconformityconfig",
        path: "/admin/NonConformityConfigurationMenu",
        icon: ListDropdown,
        dataCy: "nonConformConfig",
      },
      {
        id: "menuStatementConfig",
        labelKey: "sidenav.label.admin.formEntry.menustatementconfig",
        path: "/admin/MenuStatementConfigMenu",
        icon: Document,
        dataCy: "menuStatementConfig",
      },
      {
        id: "workPlanConfig",
        labelKey: "sidenav.label.admin.formEntry.Workplanconfig",
        path: "/admin/WorkPlanConfigurationMenu",
        icon: DataView,
        dataCy: "workPlanConfig",
      },
      {
        id: "siteInfoMenu",
        labelKey: "sidenav.label.admin.formEntry.siteInfoconfig",
        path: "/admin/SiteInformationMenu",
        icon: Devices,
        dataCy: "siteInfoMenu",
      },
      {
        id: "siteBrandingMenu",
        labelKey: "sidenav.label.admin.formEntry.siteBranding",
        path: "/admin/SiteBrandingMenu",
        icon: ColorPalette,
        dataCy: "siteBrandingMenu",
      },
      {
        id: "resultConfigMenu",
        labelKey: "sidenav.label.admin.formEntry.resultConfig",
        path: "/admin/ResultConfigurationMenu",
        icon: ResultNew,
        dataCy: "resultConfigMenu",
      },
      {
        id: "patientConfigMenu",
        labelKey: "sidenav.label.admin.formEntry.patientconfig",
        path: "/admin/PatientConfigurationMenu",
        icon: User,
        dataCy: "patientConfigMenu",
      },
      {
        id: "printedReportsConfigMenu",
        labelKey: "sidenav.label.admin.formEntry.PrintedReportsconfig",
        path: "/admin/PrintedReportsConfigurationMenu",
        icon: Report,
        dataCy: "printedReportsConfigMenu",
      },
      {
        id: "sampleEntryConfigMenu",
        labelKey: "sidenav.label.admin.formEntry.sampleEntryconfig",
        path: "/admin/SampleEntryConfigurationMenu",
        icon: TextLinkAnalysis,
        dataCy: "sampleEntryConfigMenu",
      },
      {
        id: "validationConfigMenu",
        labelKey: "sidenav.label.admin.formEntry.validationconfig",
        path: "/admin/ValidationConfigurationMenu",
        icon: ScreenOff,
        dataCy: "validationConfigMenu",
      },
    ],
  },
  {
    id: "localization",
    titleKey: "sidenav.label.admin.localization",
    defaultTitle: "Localization",
    items: [
      {
        id: "languageManagement",
        labelKey: "locale.management.title",
        defaultLabel: "Language Management",
        path: "/admin/languageManagement",
        icon: Translate,
        dataCy: "languageManagement",
      },
      {
        id: "translationManagement",
        labelKey: "translation.management.title",
        defaultLabel: "Translation Management",
        path: "/admin/translationManagement",
        icon: Translate,
        dataCy: "translationManagement",
      },
    ],
  },
  {
    id: "system",
    titleKey: "admin.section.system",
    defaultTitle: "System & Settings",
    items: [
      {
        id: "commonproperties",
        labelKey: "sidenav.label.admin.commonproperties",
        defaultLabel: "Common Properties",
        path: "/admin/commonproperties",
        icon: Settings,
      },
      {
        id: "DictionaryMenu",
        labelKey: "dictionary.label.modify",
        path: "/admin/DictionaryMenu",
        icon: Catalog,
        dataCy: "dictMenu",
      },
      {
        id: "testNotificationConfigMenu",
        labelKey: "testnotificationconfig.browse.title",
        path: "/admin/testNotificationConfigMenu",
        icon: Popup,
      },
      {
        id: "NotifyUser",
        labelKey: "notify.main.title",
        path: "/admin/NotifyUser",
        icon: Bullhorn,
        dataCy: "notifyUser",
      },
      {
        id: "SearchIndexManagement",
        labelKey: "searchindexmanagement.label",
        path: "/admin/SearchIndexManagement",
        icon: Search,
      },
      {
        id: "loggingManagement",
        labelKey: "logging.management.label",
        path: "/admin/loggingManagement",
        icon: Notification,
      },
      {
        id: "PluginFile",
        labelKey: "sidenav.label.admin.Listplugin",
        path: "/admin/PluginFile",
        icon: BootVolumeAlt,
        dataCy: "pluginFile",
      },
      {
        id: "externalConnections",
        labelKey: "externalconnections.browse.title",
        path: "/admin/externalConnections",
        icon: ConnectionSignal,
      },
      {
        id: "DatabaseCleaning",
        labelKey: "database.clean",
        path: "/admin/DatabaseCleaning",
        icon: TrashCan,
        requiresTrainingInstallation: true,
      },
    ],
  },
];

export const adminLegacyLink = {
  id: "legacyMasterLists",
  labelKey: "admin.legacy",
  href: "/MasterListsPage",
  icon: Network_2,
  openInNewWindow: true,
};

export const findAdminItemByPath = (pathname) => {
  for (const section of adminMenuSections) {
    const match = section.items.find(
      (item) => pathname === item.path || pathname.startsWith(item.path + "/"),
    );
    if (match) return { section, item: match };
  }
  return null;
};
