import React, { useState, useCallback, useEffect } from "react";
import {
  Modal,
  FileUploaderDropContainer,
  FileUploaderItem,
  Select,
  SelectItem,
  Button,
  InlineNotification,
  Tag,
  Loading,
  StructuredListWrapper,
  StructuredListHead,
  StructuredListRow,
  StructuredListCell,
  StructuredListBody,
  Accordion,
  AccordionItem,
} from "@carbon/react";
import { Upload, Checkmark, Warning, Information } from "@carbon/react/icons";
import { FormattedMessage, useIntl } from "react-intl";
import config from "../../../config.json";
import "./NotebookWorkflow.css";

/**
 * Expected dataPoints for Traditional Medicine Manifest Import.
 * Aligned with TMMRD workflow requirements for sample intake, authentication, and processing.
 * Per SRS: Sample Intake & Registration stage captures plant materials with full metadata.
 */
const EXPECTED_DATA_POINTS = {
  required: [
    {
      key: "sampleId",
      label: "Sample ID",
      description: "Unique sample identifier (assigned at intake)",
      example: "TMMRD-2024-001-A",
    },
    {
      key: "sourceType",
      label: "Source Type",
      description:
        "Source of the sample (Plant Material, Plant Extract, Formulated Product, etc.)",
      example: "Plant Material, Plant Extract",
    },
    {
      key: "scientificName",
      label: "Scientific Name",
      description: "Botanical scientific name of the plant species",
      example: "Acacia nilotica, Zingiber officinale",
    },
    {
      key: "collectionDate",
      label: "Collection Date",
      description: "Date of sample collection (YYYY-MM-DD or YYYY-MM-DD HH:MM)",
      example: "2024-01-15, 2024-01-15 09:30",
    },
    {
      key: "collectionSite",
      label: "Collection Site",
      description:
        "Geographic location where the sample was collected (origin/region)",
      example: "Addis Ababa, Eastern Ethiopia",
    },
  ],
  sampleType: {
    key: "sampleCategory",
    label: "Sample Category",
    description:
      "Category of traditional medicine sample (validated against TMMRD lab categories)",
    example: "Whole Plant, Plant Part, Extract, Formulated Product, etc.",
  },
  optional: [
    {
      key: "localName",
      label: "Local Name",
      description: "Traditional or local name of the plant",
      example: "Neem, Ginger, Turmeric",
    },
    {
      key: "plantPart",
      label: "Plant Part",
      description:
        "Part of the plant (root, leaf, stem, flower, seed, bark, etc.)",
      example: "Leaf, Root, Seed, Flower, Stem",
    },
    {
      key: "originLocation",
      label: "Origin Location",
      description: "Geographic origin or habitat where plant naturally grows",
      example: "Sub-Saharan Africa, Tropical Region",
    },
    {
      key: "collectedBy",
      label: "Collector",
      description: "Name or ID of person who collected the sample",
      example: "Dr. Getnet Bekele, Field Team A",
    },
    {
      key: "sampleCondition",
      label: "Sample Condition",
      description: "Physical state of sample (Fresh, Dried, Ground, etc.)",
      example: "Fresh, Dried, Powdered",
    },
    {
      key: "intendedUse",
      label: "Intended Use",
      description:
        "Purpose of the sample (Phytochemical analysis, Efficacy testing, Formulation, etc.)",
      example: "Phytochemical Analysis, Efficacy Testing, Formulation",
    },
    {
      key: "numOfSamples",
      label: "Number of Samples",
      description: "Quantity of samples in this batch",
      example: "5, 10",
    },
    {
      key: "notes",
      label: "Notes",
      description: "Additional notes or observations about the sample",
      example: "Sample in good condition, collected with permission",
    },
  ],
  autoGenerated: [
    {
      key: "accessionNumber",
      label: "Accession Number",
      description: "System-generated laboratory accession number",
    },
    {
      key: "barcodeQrCode",
      label: "Barcode/QR Code",
      description: "System-generated scannable identifier for tracking",
    },
  ],
};

/**
 * TraditionalMedicineManifestImportModal - CSV import modal for Traditional Medicine workflow.
 * Supports mapping traditional medicine-specific columns with field expectations display.
 * Per SRS Stage 1: Sample Intake & Registration with sample arrival, labeling, and metadata capture.
 */
function TraditionalMedicineManifestImportModal({
  open,
  onClose,
  entryId,
  onImportSuccess,
}) {
  const intl = useIntl();

  const [file, setFile] = useState(null);
  const [fileError, setFileError] = useState(null);
  const [csvHeaders, setCsvHeaders] = useState([]);
  const [columnMapping, setColumnMapping] = useState({
    sampleIdColumn: "",
    sourceTypeColumn: "",
    scientificNameColumn: "",
    collectionDateColumn: "",
    collectionSiteColumn: "",
    sampleCategoryColumn: "",
    localNameColumn: "",
    plantPartColumn: "",
    originLocationColumn: "",
    collectedByColumn: "",
    sampleConditionColumn: "",
    intendedUseColumn: "",
    numOfSamplesColumn: "",
    notesColumn: "",
  });

  const [step, setStep] = useState(1);
  const [previewData, setPreviewData] = useState(null);
  const [previewErrors, setPreviewErrors] = useState([]);
  const [isPreviewLoading, setIsPreviewLoading] = useState(false);
  const [isImporting, setIsImporting] = useState(false);

  // Sample category types fetched from backend
  const [validSampleCategories, setValidSampleCategories] = useState([]);
  const [isSampleCategoriesLoading, setIsSampleCategoriesLoading] =
    useState(false);

  /**
   * Fetch valid sample categories from backend
   */
  useEffect(() => {
    if (open) {
      setIsSampleCategoriesLoading(true);
      fetch(`${config.serverBaseUrl}/rest/notebook/tradmed/sample-categories`, {
        method: "GET",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
        credentials: "include",
      })
        .then((response) => response.json())
        .then((data) => {
          if (data && data.sampleCategories) {
            setValidSampleCategories(
              data.sampleCategories.map((sc) => sc.description || sc),
            );
          } else {
            // Fallback to hardcoded values from SRS
            setValidSampleCategories([
              "Whole Plant",
              "Plant Part",
              "Plant Extract",
              "Fractionated Extract",
              "Purified Compound",
              "Formulated Product",
              "Reference Standard",
            ]);
          }
        })
        .catch((error) => {
          console.error("Failed to fetch sample categories:", error);
          // Fallback to hardcoded values
          setValidSampleCategories([
            "Whole Plant",
            "Plant Part",
            "Plant Extract",
            "Fractionated Extract",
            "Purified Compound",
            "Formulated Product",
            "Reference Standard",
          ]);
        })
        .finally(() => {
          setIsSampleCategoriesLoading(false);
        });
    }
  }, [open]);

  /**
   * Auto-detect and map CSV columns based on header names.
   * Matches against expected column keys (case-insensitive, handles spaces/underscores/hyphens).
   */
  const autoMapColumns = useCallback((headers) => {
    // Map of expected column keys to their form field names
    const columnKeyToField = {
      sampleid: "sampleIdColumn",
      sample_id: "sampleIdColumn",
      "sample-id": "sampleIdColumn",
      id: "sampleIdColumn",
      sourcetype: "sourceTypeColumn",
      source_type: "sourceTypeColumn",
      "source-type": "sourceTypeColumn",
      source: "sourceTypeColumn",
      scientificname: "scientificNameColumn",
      scientific_name: "scientificNameColumn",
      "scientific-name": "scientificNameColumn",
      binomialname: "scientificNameColumn",
      collectiondate: "collectionDateColumn",
      collection_date: "collectionDateColumn",
      "collection-date": "collectionDateColumn",
      collecteddate: "collectionDateColumn",
      samplingdate: "collectionDateColumn",
      collectionsite: "collectionSiteColumn",
      collection_site: "collectionSiteColumn",
      "collection-site": "collectionSiteColumn",
      collectionlocation: "collectionSiteColumn",
      origin: "collectionSiteColumn",
      samplecategory: "sampleCategoryColumn",
      sample_category: "sampleCategoryColumn",
      "sample-category": "sampleCategoryColumn",
      category: "sampleCategoryColumn",
      type: "sampleCategoryColumn",
      localname: "localNameColumn",
      local_name: "localNameColumn",
      "local-name": "localNameColumn",
      commonname: "localNameColumn",
      vernacularname: "localNameColumn",
      plantpart: "plantPartColumn",
      plant_part: "plantPartColumn",
      "plant-part": "plantPartColumn",
      part: "plantPartColumn",
      originlocation: "originLocationColumn",
      origin_location: "originLocationColumn",
      "origin-location": "originLocationColumn",
      geographic_origin: "originLocationColumn",
      habitat: "originLocationColumn",
      collectedby: "collectedByColumn",
      collected_by: "collectedByColumn",
      "collected-by": "collectedByColumn",
      collector: "collectedByColumn",
      sampledby: "collectedByColumn",
      samplecondition: "sampleConditionColumn",
      sample_condition: "sampleConditionColumn",
      "sample-condition": "sampleConditionColumn",
      condition: "sampleConditionColumn",
      state: "sampleConditionColumn",
      intendeduse: "intendedUseColumn",
      intended_use: "intendedUseColumn",
      "intended-use": "intendedUseColumn",
      purpose: "intendedUseColumn",
      use: "intendedUseColumn",
      numofsamples: "numOfSamplesColumn",
      num_of_samples: "numOfSamplesColumn",
      "num-of-samples": "numOfSamplesColumn",
      numberofsamples: "numOfSamplesColumn",
      quantity: "numOfSamplesColumn",
      count: "numOfSamplesColumn",
      notes: "notesColumn",
      comments: "notesColumn",
      remarks: "notesColumn",
      observations: "notesColumn",
    };

    const newMapping = {
      sampleIdColumn: "",
      sourceTypeColumn: "",
      scientificNameColumn: "",
      collectionDateColumn: "",
      collectionSiteColumn: "",
      sampleCategoryColumn: "",
      localNameColumn: "",
      plantPartColumn: "",
      originLocationColumn: "",
      collectedByColumn: "",
      sampleConditionColumn: "",
      intendedUseColumn: "",
      numOfSamplesColumn: "",
      notesColumn: "",
    };

    headers.forEach((header) => {
      // Normalize header: lowercase, remove spaces/underscores/hyphens
      const normalizedHeader = header
        .toLowerCase()
        .replace(/[\s_-]/g, "")
        .replace(/[/\\]/g, "");

      const fieldName = columnKeyToField[normalizedHeader];
      if (fieldName) {
        newMapping[fieldName] = header;
      }
    });

    return newMapping;
  }, []);

  const handleFileAdded = useCallback(
    (_event, { addedFiles }) => {
      const addedFile = addedFiles[0];
      if (!addedFile) return;

      if (!addedFile.name.endsWith(".csv")) {
        setFileError(
          intl.formatMessage({
            id: "notebook.tradmed.manifest.error.invalidFileType",
            defaultMessage: "Please upload a CSV file",
          }),
        );
        return;
      }

      setFile(addedFile);
      setFileError(null);

      const reader = new FileReader();
      reader.onload = (e) => {
        const text = e.target.result;
        const firstLine = text.split("\n")[0];
        const headers = firstLine
          .split(",")
          .map((h) => h.trim().replace(/"/g, ""));
        setCsvHeaders(headers);

        // Auto-map columns based on header names
        const autoMappedColumns = autoMapColumns(headers);
        setColumnMapping(autoMappedColumns);

        setStep(2);
      };
      reader.readAsText(addedFile);
    },
    [intl, autoMapColumns],
  );

  const handleRemoveFile = () => {
    setFile(null);
    setCsvHeaders([]);
    setColumnMapping({
      sampleIdColumn: "",
      sourceTypeColumn: "",
      scientificNameColumn: "",
      collectionDateColumn: "",
      collectionSiteColumn: "",
      sampleCategoryColumn: "",
      localNameColumn: "",
      plantPartColumn: "",
      originLocationColumn: "",
      collectedByColumn: "",
      sampleConditionColumn: "",
      intendedUseColumn: "",
      numOfSamplesColumn: "",
      notesColumn: "",
    });
    setPreviewData(null);
    setPreviewErrors([]);
    setStep(1);
  };

  const handleMappingChange = (field, value) => {
    setColumnMapping((prev) => ({ ...prev, [field]: value }));
  };

  // Required fields per SRS: sampleId, sourceType, scientificName, collectionDate, collectionSite
  const requiredColumnsMapped =
    columnMapping.sampleIdColumn &&
    columnMapping.sourceTypeColumn &&
    columnMapping.scientificNameColumn &&
    columnMapping.collectionDateColumn &&
    columnMapping.collectionSiteColumn;

  const buildFormData = () => {
    const formData = new FormData();
    formData.append("file", file);
    formData.append(
      "mapping",
      new Blob([JSON.stringify(columnMapping)], { type: "application/json" }),
    );
    return formData;
  };

  const handlePreview = async () => {
    if (!file || !entryId) return;
    setIsPreviewLoading(true);
    setPreviewErrors([]);

    try {
      const endpoint = `${config.serverBaseUrl}/rest/notebook/tradmed/entry/${entryId}/samples/preview-manifest`;
      const response = await fetch(endpoint, {
        method: "POST",
        body: buildFormData(),
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      });

      const data = await response.json();
      if (response.ok) {
        setPreviewData(data);
        setPreviewErrors(data.errors || []);
        setStep(3);
      } else {
        setPreviewErrors(
          data.errors || [
            {
              rowNumber: 0,
              column: "file",
              message: data.error || "Preview failed",
            },
          ],
        );
      }
    } catch (error) {
      setPreviewErrors([
        { rowNumber: 0, column: "file", message: error.message },
      ]);
    } finally {
      setIsPreviewLoading(false);
    }
  };

  const handleImport = async () => {
    if (!file || !entryId) return;
    setIsImporting(true);
    setPreviewErrors([]);

    try {
      const endpoint = `${config.serverBaseUrl}/rest/notebook/tradmed/entry/${entryId}/samples/create-from-manifest`;
      const response = await fetch(endpoint, {
        method: "POST",
        body: buildFormData(),
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      });

      const data = await response.json();
      if (response.ok && data.success) {
        setStep(4);
        if (onImportSuccess) {
          onImportSuccess(data);
        }
      } else {
        setPreviewErrors(
          data.errors || [
            {
              rowNumber: 0,
              column: "import",
              message: data.error || "Import failed",
            },
          ],
        );
      }
    } catch (error) {
      setPreviewErrors([
        { rowNumber: 0, column: "import", message: error.message },
      ]);
    } finally {
      setIsImporting(false);
    }
  };

  const handleClose = () => {
    handleRemoveFile();
    onClose();
  };

  const mappingField = (field, labelId, required = false) => (
    <div className={`mapping-field ${required ? "required" : ""}`}>
      <Select
        id={`mapping-${field}`}
        labelText={intl.formatMessage({ id: labelId })}
        value={columnMapping[field]}
        onChange={(e) => handleMappingChange(field, e.target.value)}
      >
        <SelectItem
          value=""
          text={intl.formatMessage({ id: "label.select" })}
        />
        {csvHeaders.map((header) => (
          <SelectItem key={header} value={header} text={header} />
        ))}
      </Select>
      {required && <span className="required-marker">*</span>}
    </div>
  );

  return (
    <Modal
      open={open}
      onRequestClose={handleClose}
      modalHeading={intl.formatMessage({
        id: "notebook.tradmed.manifest.title",
        defaultMessage: "Import Traditional Medicine Samples from Manifest",
      })}
      primaryButtonText={
        step === 1
          ? intl.formatMessage({ id: "label.button.next" })
          : step === 2
            ? intl.formatMessage({ id: "notebook.manifest.preview" })
            : step === 3
              ? intl.formatMessage({ id: "notebook.manifest.import" })
              : intl.formatMessage({ id: "label.button.close" })
      }
      secondaryButtonText={
        step > 1 && step < 4
          ? intl.formatMessage({ id: "label.button.back" })
          : null
      }
      onRequestSubmit={() => {
        if (step === 1 && file) setStep(2);
        else if (step === 2) handlePreview();
        else if (step === 3) handleImport();
        else handleClose();
      }}
      onSecondarySubmit={() => setStep(step - 1)}
      primaryButtonDisabled={
        (step === 1 && !file) ||
        (step === 2 && !requiredColumnsMapped) ||
        (step === 3 && previewErrors.length > 0) ||
        isPreviewLoading ||
        isImporting
      }
      size="md"
    >
      <div className="manifest-import-modal">
        {step === 1 && (
          <div className="upload-step">
            <p className="step-description">
              <FormattedMessage
                id="notebook.tradmed.manifest.step1"
                defaultMessage="Upload a CSV file with traditional medicine sample metadata. Review the expected data points below before uploading."
              />
            </p>

            {/* Expected Data Points Section */}
            <Accordion className="expected-datapoints-accordion">
              <AccordionItem
                title={
                  <span className="accordion-title">
                    <Information size={16} />
                    <FormattedMessage
                      id="notebook.tradmed.manifest.expectedColumns"
                      defaultMessage="Expected CSV Columns &amp; Data Points"
                    />
                  </span>
                }
                open={!file}
              >
                <div className="datapoints-container">
                  {/* Required Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title required-title">
                      <FormattedMessage
                        id="notebook.tradmed.manifest.requiredFields"
                        defaultMessage="Required Fields"
                      />
                      <Tag type="red" size="sm">
                        {EXPECTED_DATA_POINTS.required.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.example"
                              defaultMessage="Example"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.required.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                              <br />
                              <code className="column-key">{field.key}</code>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                            <StructuredListCell>
                              <code>{field.example}</code>
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Sample Category Field (Validated) */}
                  <div className="datapoints-section">
                    <h5 className="section-title sampletype-title">
                      <FormattedMessage
                        id="notebook.tradmed.manifest.sampleCategoryField"
                        defaultMessage="Sample Category (Validated)"
                      />
                      <Tag type="purple" size="sm">
                        1
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="notebook.tradmed.manifest.validValues"
                              defaultMessage="Valid Values"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        <StructuredListRow>
                          <StructuredListCell>
                            <strong>
                              {EXPECTED_DATA_POINTS.sampleType.label}
                            </strong>
                            <br />
                            <code className="column-key">
                              {EXPECTED_DATA_POINTS.sampleType.key}
                            </code>
                          </StructuredListCell>
                          <StructuredListCell>
                            {EXPECTED_DATA_POINTS.sampleType.description}
                          </StructuredListCell>
                          <StructuredListCell>
                            <div className="valid-values-list">
                              {isSampleCategoriesLoading ? (
                                <Loading
                                  small
                                  description={intl.formatMessage({
                                    id: "notebook.tradmed.manifest.loadingCategories",
                                    defaultMessage: "Loading categories...",
                                  })}
                                />
                              ) : validSampleCategories.length > 0 ? (
                                validSampleCategories.map((category) => (
                                  <Tag
                                    key={category}
                                    type="outline"
                                    size="sm"
                                    className="valid-value-tag"
                                  >
                                    {category}
                                  </Tag>
                                ))
                              ) : (
                                <span>
                                  <FormattedMessage
                                    id="notebook.tradmed.manifest.noCategories"
                                    defaultMessage="No categories available"
                                  />
                                </span>
                              )}
                            </div>
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Optional Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title optional-title">
                      <FormattedMessage
                        id="notebook.tradmed.manifest.optionalFields"
                        defaultMessage="Optional Fields"
                      />
                      <Tag type="blue" size="sm">
                        {EXPECTED_DATA_POINTS.optional.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.example"
                              defaultMessage="Example"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.optional.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                              <br />
                              <code className="column-key">{field.key}</code>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                            <StructuredListCell>
                              <code>{field.example}</code>
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Auto-Generated Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title autogenerated-title">
                      <FormattedMessage
                        id="notebook.tradmed.manifest.autoGeneratedFields"
                        defaultMessage="Auto-Generated Fields (NOT in CSV)"
                      />
                      <Tag type="green" size="sm">
                        {EXPECTED_DATA_POINTS.autoGenerated.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.autoGenerated.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>
                </div>
              </AccordionItem>
            </Accordion>

            {!file ? (
              <FileUploaderDropContainer
                accept={[".csv"]}
                labelText={intl.formatMessage({
                  id: "notebook.tradmed.manifest.dropzone",
                  defaultMessage:
                    "Drag and drop a CSV file here or click to upload",
                })}
                onAddFiles={handleFileAdded}
              />
            ) : (
              <FileUploaderItem
                name={file.name}
                status="edit"
                onDelete={handleRemoveFile}
              />
            )}
            {fileError && (
              <InlineNotification
                kind="error"
                title={fileError}
                lowContrast
                hideCloseButton
              />
            )}
          </div>
        )}

        {step === 2 && (
          <div className="mapping-step">
            <p className="step-description">
              <FormattedMessage
                id="notebook.tradmed.manifest.step2"
                defaultMessage="Map CSV columns to traditional medicine sample fields. Required fields are marked with *."
              />
            </p>
            <div className="mapping-grid">
              {/* Required Fields Section */}
              <h5 className="section-heading required-heading">
                <Tag type="red" size="sm">
                  <FormattedMessage
                    id="notebook.tradmed.manifest.requiredFields"
                    defaultMessage="Required Fields"
                  />
                </Tag>
              </h5>
              {mappingField(
                "sampleIdColumn",
                "notebook.tradmed.manifest.column.sampleId",
                true,
              )}
              {mappingField(
                "sourceTypeColumn",
                "notebook.tradmed.manifest.column.sourceType",
                true,
              )}
              {mappingField(
                "scientificNameColumn",
                "notebook.tradmed.manifest.column.scientificName",
                true,
              )}
              {mappingField(
                "collectionDateColumn",
                "notebook.tradmed.manifest.column.collectionDate",
                true,
              )}
              {mappingField(
                "collectionSiteColumn",
                "notebook.tradmed.manifest.column.collectionSite",
                true,
              )}

              {/* Sample Category Field (Validated) */}
              <h5 className="section-heading sampletype-heading">
                <Tag type="purple" size="sm">
                  <FormattedMessage
                    id="notebook.tradmed.manifest.sampleCategoryField"
                    defaultMessage="Sample Category (Validated)"
                  />
                </Tag>
              </h5>
              <div className="mapping-field info-message">
                <p>
                  <Information size={16} />
                  <FormattedMessage
                    id="notebook.tradmed.manifest.categoryValidationInfo"
                    defaultMessage="Sample category must match one of the valid TMMRD lab categories. Invalid categories will be rejected during validation."
                  />
                </p>
              </div>
              {mappingField(
                "sampleCategoryColumn",
                "notebook.tradmed.manifest.column.sampleCategory",
              )}

              {/* Optional Fields Section */}
              <h5 className="section-heading optional-heading">
                <Tag type="blue" size="sm">
                  <FormattedMessage
                    id="notebook.tradmed.manifest.optionalFields"
                    defaultMessage="Optional Fields"
                  />
                </Tag>
              </h5>
              {mappingField(
                "localNameColumn",
                "notebook.tradmed.manifest.column.localName",
              )}
              {mappingField(
                "plantPartColumn",
                "notebook.tradmed.manifest.column.plantPart",
              )}
              {mappingField(
                "originLocationColumn",
                "notebook.tradmed.manifest.column.originLocation",
              )}
              {mappingField(
                "collectedByColumn",
                "notebook.tradmed.manifest.column.collectedBy",
              )}
              {mappingField(
                "sampleConditionColumn",
                "notebook.tradmed.manifest.column.sampleCondition",
              )}
              {mappingField(
                "intendedUseColumn",
                "notebook.tradmed.manifest.column.intendedUse",
              )}
              {mappingField(
                "numOfSamplesColumn",
                "notebook.tradmed.manifest.column.numOfSamples",
              )}
              {mappingField(
                "notesColumn",
                "notebook.tradmed.manifest.column.notes",
              )}
            </div>
            {previewErrors.length > 0 && (
              <InlineNotification
                kind="error"
                title={intl.formatMessage({
                  id: "notebook.manifest.validationErrors",
                  defaultMessage: "Validation Errors",
                })}
                subtitle={
                  <ul className="error-list">
                    {previewErrors.map((error, idx) => (
                      <li key={idx}>
                        {error.rowNumber > 0 ? `Row ${error.rowNumber}: ` : ""}
                        {error.message}
                      </li>
                    ))}
                  </ul>
                }
                lowContrast
                hideCloseButton
              />
            )}
          </div>
        )}

        {step === 3 && (
          <div className="preview-step">
            {isPreviewLoading ? (
              <Loading withOverlay={false} description="Loading preview..." />
            ) : (
              <>
                {previewErrors.length > 0 && (
                  <InlineNotification
                    kind="error"
                    title={intl.formatMessage({
                      id: "notebook.manifest.validationErrors",
                      defaultMessage: "Validation Errors",
                    })}
                    subtitle={
                      <ul className="error-list">
                        {previewErrors.map((error, idx) => (
                          <li key={idx}>
                            {error.rowNumber > 0
                              ? `Row ${error.rowNumber}: `
                              : ""}
                            {error.message}
                          </li>
                        ))}
                      </ul>
                    }
                    lowContrast
                    hideCloseButton
                  />
                )}

                {previewData && previewErrors.length === 0 && (
                  <div className="preview-summary">
                    <Tag type="blue">
                      <FormattedMessage
                        id="notebook.manifest.preview.rows"
                        defaultMessage="{count} rows"
                        values={{ count: previewData.totalRows }}
                      />
                    </Tag>
                    <Tag type="green">
                      <FormattedMessage
                        id="notebook.manifest.preview.samples"
                        defaultMessage="{count} samples to create"
                        values={{ count: previewData.totalSamplesToCreate }}
                      />
                    </Tag>
                  </div>
                )}
              </>
            )}
          </div>
        )}

        {step === 4 && (
          <div className="success-step">
            <Checkmark size={48} className="success-icon" />
            <h3>
              <FormattedMessage
                id="notebook.manifest.success.title"
                defaultMessage="Import Successful"
              />
            </h3>
            <p>
              <FormattedMessage
                id="notebook.manifest.success.message"
                defaultMessage="Samples have been created and linked to the notebook entry."
              />
            </p>
          </div>
        )}
      </div>
    </Modal>
  );
}

export default TraditionalMedicineManifestImportModal;
